### ISSUE TITLE
Can't disable extensions

### ISSUE THREAD

**Issue by VPNforWindowsSub** [Delusoire/bespoke#3]
Disabling extensions on Spotify is not working, and when I reopen the app, the extension re-enables.
I'm aware that I can edit "vault.json" to enable/disable extensions.

also can't use spicetify and bespoke at the same time, Is there any way to install spicetify extensions in bespoke?
I only need 'sort-plus', and since you haven't updated the 'Delusoire/spicetify-extensions' version, I am forced to install bespoke. But now, I'm missing other extensions. If only I could use the updated 'sort-plus' in spicetify, that would be awesome.

**Comment by Delusoire** [comment]
You can't toggle modules directly from spotify for now because I still haven't hosted the proxy server that handles bespoke's custom uri scheme, the code for it is already finished and you can run it locally if you wish.

Bespoke is probably going to be released as the next major release of spicetify. Meaning it's not going to be backwards compatible with the older extensions, but they can all be ported with minimal effort.

I'm curious as to which extensions/themes/custom apps you're using. I may port them to bespoke if they're popular enough.
